"use client";
import {useEffect,useState} from "react";
type Cat={_id:string,name:string,emoji:string}; type Prod={_id:string,name:string,description:string,price:number,stock:number,categoryId:any,imageUrl:string};
export default function Admin(){
 const [tab,setTab]=useState("products"),[cats,setCats]=useState<Cat[]>([]),[prods,setProds]=useState<Prod[]>([]),[s,setS]=useState<any>({}),[msg,setMsg]=useState("");
 async function load(){const [c,p,st]=await Promise.all([fetch("/api/admin/categories"),fetch("/api/admin/products"),fetch("/api/admin/settings")]);if([c,p,st].some(x=>x.status===401)){location.href="/";return}setCats(await c.json());setProds(await p.json());setS(await st.json())}
 useEffect(()=>{load()},[]);
 async function addCat(){const name=prompt("Nama kategori?");if(!name)return;await fetch("/api/admin/categories",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,emoji:"📦"})});load()}
 async function delCat(id:string){if(confirm("Hapus kategori?")){await fetch("/api/admin/categories?id="+id,{method:"DELETE"});load()}}
 async function addProd(){const name=prompt("Nama produk?");if(!name||!cats[0])return alert("Buat kategori dulu.");const price=Number(prompt("Harga (angka)?","10000"));const stock=Number(prompt("Stok?","1"));await fetch("/api/admin/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,price,stock,categoryId:cats[0]._id,description:"",active:true})});load()}
 async function delProd(id:string){if(confirm("Hapus produk?")){await fetch("/api/admin/products?id="+id,{method:"DELETE"});load()}}
 async function save(){await fetch("/api/admin/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(s)});setMsg("Tersimpan ✓");setTimeout(()=>setMsg(""),1800)}
 return <main className="shell"><nav className="nav"><div className="brand">🟩 ServicesId Store</div><div className="row"><span className="small">{msg}</span><button className="btn secondary" onClick={()=>fetch("/api/admin/logout",{method:"POST"}).then(()=>location.href="/")}>Keluar</button></div></nav><div className="wrap">
 <div className="tabs">{[["products","🛍 Produk"],["categories","🗂 Kategori"],["appearance","🎨 Tampilan"]].map(x=><button className="btn secondary" onClick={()=>setTab(x[0])}>{x[1]}</button>)}</div>
 {tab==="products"&&<div className="card"><div className="row" style={{justifyContent:"space-between"}}><h2>Produk</h2><button className="btn" onClick={addProd}>+ Tambah</button></div><table className="table"><thead><tr><th>Produk</th><th>Harga</th><th>Stok</th><th></th></tr></thead><tbody>{prods.map(p=><tr key={p._id}><td>{p.name}</td><td>Rp{(p.price||0).toLocaleString("id-ID")}</td><td>{p.stock}</td><td><button className="btn danger" onClick={()=>delProd(p._id)}>Hapus</button></td></tr>)}</tbody></table></div>}
 {tab==="categories"&&<div className="card"><div className="row" style={{justifyContent:"space-between"}}><h2>Kategori</h2><button className="btn" onClick={addCat}>+ Tambah</button></div>{cats.map(c=><div className="row pill" style={{justifyContent:"space-between",margin:"8px 0"}} key={c._id}><span>{c.emoji} {c.name}</span><button className="btn danger" onClick={()=>delCat(c._id)}>Hapus</button></div>)}</div>}
 {tab==="appearance"&&<div className="grid"><div className="card"><h2>Tampilan Bot</h2><label>Nama Store</label><input className="input" value={s.storeName||""} onChange={e=>setS({...s,storeName:e.target.value})}/><label>Tagline</label><input className="input" value={s.tagline||""} onChange={e=>setS({...s,tagline:e.target.value})}/><label>Teks sambutan</label><textarea className="input" rows={4} value={s.welcomeText||""} onChange={e=>setS({...s,welcomeText:e.target.value})}/><label>URL Logo</label><input className="input" value={s.logoUrl||""} onChange={e=>setS({...s,logoUrl:e.target.value})}/><label>URL Banner/Background</label><input className="input" value={s.bannerUrl||""} onChange={e=>setS({...s,bannerUrl:e.target.value})}/><label>Warna utama</label><input className="input" value={s.primaryColor||"#16a34a"} onChange={e=>setS({...s,primaryColor:e.target.value})}/><button className="btn" onClick={save}>Simpan Pengaturan</button></div><div className="card"><h2>Preview</h2><div className="preview" style={{background:s.bannerUrl?`url(${s.bannerUrl}) center/cover`:"#07110b",padding:20}}><h2 style={{color:s.primaryColor||"#4ade80"}}>{s.storeName||"ServicesId Store"}</h2><p>{s.welcomeText}</p><button className="btn">🛍 Produk</button></div><p className="small">Telegram sendiri tidak mengizinkan bot mengubah warna latar/warna teks chat seperti website. Desain dibuat melalui emoji, banner, logo, gambar, dan inline keyboard.</p></div></div>}
 </div></main>
}
